# Generated by Django 2.0.5 on 2018-05-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summer',
            new_name='summery',
        ),
    ]
